### ISSUE TITLE
Blacklisting error

### ISSUE THREAD

**Issue by BobSemple** [Lexiebean/TurtleMenagerie#1]
I get the following error when I try to blacklist a pet:
`TurtleMenagerie.lua:88:attempt to call global 'strmatch' (a nil value)`

**Comment by Lexiebean** [comment]
What pet were you trying to blacklist?  
What was the command that you typed?

**Comment by BobSemple** [comment]
/randpet bl Black Piglet
I also tried by linking the spell from the spellbook, but then I found that regardless what I write after the command I get the same error.

**Comment by Lexiebean** [comment]
I think the strmatch function was being added by one of my other addons (HealComm).

I've uploaded a potential fix but no time to test it myself. (Should have left for work 10mins ago...)

**Comment by BobSemple** [comment]
Thanks a lot, it works. :)
